### ISSUE TITLE
missing dependency for matplotlib

### ISSUE THREAD

**Issue by drammock** [LABSN/new-computer-setup#13]
`libfreetype6-dev` is a dependency when building `matplotlib` locally (from cloned git repo)

**Comment by rkmaddox** [comment]
Is there a reason to build `matplotlib` oneself?

**Comment by drammock** [comment]
Not usually.  But in my case, trying to install from repos it doesn't seem to know that I already have a local compile of numpy, and tries to pull down the repo numpy, which causes havoc.

**Comment by drammock** [comment]
apparently `libfreetype6-dev` was already included the "general dependencies" section of the build script.
